import Layout from "../components/Layout";
import AnimatedText from "../components/AnimatedText";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import profilePic from "../../public/images/profile/profilePic.png";
import { LinkArrow } from "../components/Icons";
import HireMe from "../components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Abdulkareem Abunabhan</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Abdulkareem"
                className="h-auto w-85 lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center">
              <AnimatedText text="Turning Ideas into Real Solutions by Code and Innovation." className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"/>
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
              As a dedicated full-stack developer, I am committed to translating your ideas into practical web applications that solve real-world challenges. Explore my latest projects, showcasing my expertise in React.js and problem-solving in web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/DocumentsAbdulkareem_abunabhan (1).pdf"
                  target={"_blank"}
                  className="dark:bg-light dark:text-dark hover:dark:bg-dark md:p-2 md:px-4 md:text-base hover:dark:border-light hover:dark:text-light flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:zman17881@gmail.com" target={"_blank"} className="ml-4 text-lg font-medium underline capitalize md:text-base dark:text-light text-dark">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute inline-block w-24 right-8 bottom-8 md:hidden">
          <Image src={lightBulb} alt="Abdulkareem Abunabhan" className="w-full h-auto"/>
        </div>
      </main>
    </>
  );
}
